### ISSUE TITLE
请问技术胖，fluro传递中文参数报错的问题怎么解决？

### ISSUE THREAD

**Issue by lanjiachuan** [kukyxs/flutter_shop#1]
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following ArgumentError was thrown while handling a gesture:
flutter: Invalid argument(s): Illegal percent encoding in URI
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _Uri._uriDecode (dart:core/uri.dart:2836:11)
flutter: #1      Uri.decodeComponent (dart:core/uri.dart:1117:17)
flutter: #2      RouteTree.parseQueryString.decode (package:fluro/src/tree.dart:225:29)
flutter: #3      RouteTree.parseQueryString (package:fluro/src/tree.dart:228:28)
flutter: #4      RouteTree.matchRoute (package:fluro/src/tree.dart:132:22)
flutter: #5      Router.matchRoute (package:fluro/src/router.dart:103:38)

**Comment by kukyxs** [comment]
1. 首先我不是技术胖哟，我就是买了技术胖的课程，技术胖的项目地址戳这 [flutter_shop](https://github.com/shenghy/flutter_shop)
2. fluro 传递中文值需要先进行转码再进行传递，转码和解码可以参考我自己写的方法 [fluro_convert_util](https://github.com/kukyxs/flutter_weather/blob/master/lib/utils/fluro_convert_util.dart)

**Comment by Quanhua-Guan** [comment]
```
text = Uri.encodeQueryComponent(text);
```
